# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.2.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-08-10T01:51:46Z"
  labels:
    app: flask-mysql-pod
  name: flask-mysql-pod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - cd src && python3 run.py
    env:
    - name: PATH
      value: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: PYTHON_GET_PIP_URL
      value: https://github.com/pypa/get-pip/raw/c20b0cfd643cd4a19246ccf204e2997af70f6b21/public/get-pip.py
    - name: GPG_KEY
      value: E3FF2839C048B25C084DEBE9B26995E310250568
    - name: PYTHON_VERSION
      value: 3.9.6
    - name: PYTHON_PIP_VERSION
      value: 21.2.3
    - name: PYTHON_GET_PIP_SHA256
      value: fa6f3fb93cce234cd4e8dd2beb54a51ab9c247653b52855a48dd44e6b21ff28b
    - name: LANG
      value: C.UTF-8
    image: localhost/flask-rest-api-mysql-v1.2:latest
    name: flask-rest-api-pod-version
    ports:
    - containerPort: 5000
      hostPort: 5000
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /flask-rest-api
  - args:
    - --default-authentication-plugin=mysql_native_password
    command:
    - docker-entrypoint.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: MYSQL_MAJOR
      value: "8.0"
    - name: MYSQL_VERSION
      value: 8.0.26-1debian10
    - name: MYSQL_ROOT_PASSWORD
      value: admin
    - name: MYSQL_DATABASE
      value: Colors_flask_api
    - name: GOSU_VERSION
      value: "1.12"
    image: docker.io/library/mysql:latest
    name: mysql-db-pod-version
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
  dnsConfig: {}
  restartPolicy: Always
status: {}

